### ISSUE TITLE
rehash.mo;  missing   nat32ToNat64;   nat64ToNat32;

### ISSUE THREAD

**Issue by s1dc0des** [ZhenyaUsenko/motoko-hash-map#10]
<img width="370" alt="Screenshot 2023-10-14 at 12 35 10 PM" src="https://github.com/ZhenyaUsenko/motoko-hash-map/assets/57266826/f9d43c99-f799-42b2-acee-510ef18ba39c">

these seem to be missing in motoko 0.10.0

**Comment by ZhenyaUsenko** [comment]
Hi. These methods were included in 0.9.8

Release notes https://github.com/dfinity/motoko/releases/tag/0.9.8
Pull request https://github.com/dfinity/motoko/pull/4139
Code https://github.com/dfinity/motoko/blob/master/src/prelude/prim.mo#L144

What were your steps to ensure you are building with Motoko compiler 0.10.0? Please look through this issue https://github.com/ZhenyaUsenko/motoko-hash-map/issues/9

**Comment by s1dc0des** [comment]
updated dfx works now. nice
