### ISSUE TITLE
 Field append is deprecated

### ISSUE THREAD

**Issue by samlinux** [ZhenyaUsenko/motoko-hash-map#11]
Hi, I would like to info you about the following warning using your motoko-hash-map implementation:

WARN: .mops/base@0.10.2/src/Principal.mo:80.20-80.32: warning [M0154], field append is deprecated:
`Array.append` copies its arguments and has linear complexity;

dfx versin 0.15.2

**Comment by ZhenyaUsenko** [comment]
Looking at the warning message you provided, it comes from the **base** package, specifically **toLedgerAccount** function in the **Principal.mo** file.

https://github.com/dfinity/motoko-base/blob/master/src/Principal.mo

**Comment by samlinux** [comment]
Thanks, I have mentioned this library in my last article.

https://blog.icacademy.at/blog/astro-svelte-ic-starter
