### ISSUE TITLE
How do I add this to a project so that import Map "mo:hashmap/Map"; works?

### ISSUE THREAD

**Issue by nbilbeny** [ZhenyaUsenko/motoko-hash-map#2]
What are the steps to integrate this repo into an existing project?

I tried `mops add hashmap` but no luck.

Also tried 

```
// From https://github.com/ZhenyaUsenko/motoko-hash-map
import Map "motoko-hash-map/src/Map/Map";
```

but then I see:
<img width="878" alt="image" src="https://user-images.githubusercontent.com/13382230/213213652-f8b47de9-0ce8-4bf9-9518-6b03bb837396.png">

**Comment by ZhenyaUsenko** [comment]
You are probably using version v8.0.0-rc2 (master branch).
The docs is for the latest non-pre-release version (v7.0.0).
So you can either use v7 or adjust the line above to
`stable var users_map = Map.new<Principal, UserData>(Map.phash)`

**Comment by nbilbeny** [comment]
Thanks. That works.

However, I'm importing like this:

`import Map "motoko-hash-map/src/Map/Map";
`

What can I do to import instead like this but without an error?

<img width="300" alt="image" src="https://user-images.githubusercontent.com/13382230/213313689-fae2bb9b-e8b5-4761-95d0-a20ed0c6c2cf.png">

In other words, how do I add the repo to my project without manually copying and pasting the folders into the project?

**Comment by ZhenyaUsenko** [comment]
Maybe you have your **vessel** misconfigured. Can you share the contents of your *vessel.dhall* and *package-set.dhall* files?

**Comment by nbilbeny** [comment]
Oh, I didn't know this uses vessel. I've not used vessel. Only mops.
