### ISSUE TITLE
not working after update

### ISSUE THREAD

**Issue by paulous** [ZhenyaUsenko/motoko-hash-map#9]
I am getting this error after updating:
Stderr:
```
.mops/map@9.0.0/src/Map/modules/rehash.mo:3.82-3.94: type error [M0119], object field nat32ToNat64 is not contained in expected type
  module {}
```

thanks!

**Comment by ZhenyaUsenko** [comment]
Hi. Map v9 requires the latest Motoko Compiler (v0.9.8)
https://github.com/dfinity/motoko/releases/tag/0.9.8

**Comment by ZhenyaUsenko** [comment]
If you are using vessel, use the next config
```
{
  dependencies = [
    ...
  ],
  compiler = Some "0.9.8",
}
```

And then deploy with

`DFX_MOC_PATH=$(vessel bin)/moc dfx deploy`

**Comment by paulous** [comment]
Ok thanks! I am using dfx 0.14.4 . I am just experimenting with stuff and not too deep into it, so I guess I will have to wait until the motoko compiler is updated maybe.
